### PR TITLE
Some things

### PR DESCRIPTION
**Pull request by johnskopis**
First, thanks for making such a great plugin. I noticed the site includes a factual rating and was curious how hard it would be to add to the plugin. 

The first two commits are useful are pretty straightforward.
The cache/validator stuff was helpful when I was tweaking the xpath rules. I completely understand if you don't want to add it. Let me know...

Thanks

### CODE REVIEW

**Comment by JeffreyATW** [comment]
Everything looks pretty good - would you mind updating the `.ruby-version` file to specify `2.4.1` as well?

**Comment by johnskopis** [comment]
done!

**Comment by JeffreyATW** [comment]
Thank you!

**Comment by JeffreyATW** [comment]
I’ll get to updating my hosted version in the morning.

**Comment by johnskopis** [comment]
Word! Unless I did something wrong there's 2027 sources vs 1292 previously:
`jq '. | keys | length' output/sources.json => 2027`
`jq '. | keys | length' jeff.json => 1292`

**Comment by JeffreyATW** [comment]
That might be because the cron job on my host is busted and probably hasn't run in a long time.

**Comment by JeffreyATW** [comment]
OK, crawl has run, and I've edited my cron job so hopefully future crawls actually take place.

**Comment by johnskopis** [comment]
:+1:

**Pull request merged**
